spring:
  datasource:
    url: ${OPEN_GAUSS_URL}
    username: ${OPEN_GAUSS_USER}
    password: ${OPEN_GAUSS_PASSWORD}
    driver-class-name: org.opengauss.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 验证连接有效性
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 配置连接失败重试次数
      connection-error-retry-attempts: 3
      break-after-acquire-failure: false
      # 配置获取连接等待超时后的重试间隔
      time-between-connect-error-millis: 5000
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 5000ms  # 连接超时和读写超时时间
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
        shutdown-timeout: 0ms  # 优雅关闭连接
      database: 2
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
rsa:
  key-pairs:
    pair1:
      private-key: ${PRIVATE_KEY1}
      public-key: ${PUBLIC_KEY1}
    pair2:
      private-key: ${PRIVATE_KEY2}
      public-key: ${PUBLIC_KEY2}

server:
  port: ${SERVER_PORT}
  address: 0.0.0.0

mybatis-plus:
  type-handlers-package: com.qg.handler
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: true
  global-config:
    db-config:
          id-type: auto
          logic-not-delete-value: 0
          logic-delete-field: is_deleted
          logic-delete-value: 1

