server:
  port: 8094
feign:
  okhttp:
    enabled: true
spring:
  mail:
    host: smtp.qq.com
    port: 587
    username: 2864201368@qq.com
    password: onehhunksqknddfc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


#logging:
#  level:
#    com.alibaba.nacos: TRACE
#    com.alibaba.cloud.nacos: TRACE
#    org.springframework.cloud: DEBUG
#    org.springframework.web: DEBUG